apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager-token
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: github-runner-secrets
    kind: ClusterSecretStore
  target:
    name: controller-manager
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: github_token
      remoteRef:
        key: org-runner
        property: github_token
