apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: org-runners
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      organization: jLemmings
      image: ghcr.io/actions/actions-runner:latest
      labels:
        - self-hosted
        - linux
        - x64
      githubTokenRef:
        name: github-runner-credentials
        key: github_token
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
      dockerdWithinRunnerContainer: true
